"""initial tables

Revision ID: b2624fd177fa
Revises: 
Create Date: 2026-08-19 14:46:35.266658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2624fd177fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'attempt', name='uq_application_attempt')
    )
    op.create_index(op.f('ix_application_attempts_application_id'), 'application_attempts', ['application_id'], unique=False)
    op.create_table('application_state_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('workflow_run_id', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'workflow_run_id', 'state', name='uq_application_state')
    )
    op.create_index(op.f('ix_application_state_history_application_id'), 'application_state_history', ['application_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('platform_job_id', sa.String(), nullable=False),
    sa.Column('actionable', sa.Boolean(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_job_id', name='uq_job_platform_id')
    )
    op.create_index(op.f('ix_jobs_actionable'), 'jobs', ['actionable'], unique=False)
    op.create_index(op.f('ix_jobs_platform'), 'jobs', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_platform'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_actionable'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_application_state_history_application_id'), table_name='application_state_history')
    op.drop_table('application_state_history')
    op.drop_index(op.f('ix_application_attempts_application_id'), table_name='application_attempts')
    op.drop_table('application_attempts')
    # ### end Alembic commands ###
